version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://exampleuser:examplepass@db:5432/postgres
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./frontend/shop_admin_app:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data: